import { createStyles } from '@material-ui/styles';
import theme from '../../theme';

const styles = createStyles({
  business: {
    position: 'relative',
    backgroundImage: 'url("images/back1.png")',
    backgroundSize: 'cover',
    height: '850px',
    padding: '215px 135px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    color: 'white',
    '& > div:first-child': {
      display: 'flex',
      alignItems: 'center',
      '& > span': {
        fontSize: '17px',
        lineHeight: '25px',
        paddingLeft: '15px',
      }
    },
    '& > span': {
      fontSize: '65px',
      fontWeight: 'bold',
      lineHeight: '75px',
      letterSpacing: '-1px',
      zIndex: '1',
      '& > span': {
        textDecorationLine: 'underline',
      },
    },
    '& > p': {
      maxWidth: '830px',
      margin: '0',
      fontSize: '30px',
      lineHeight: '40px',
      zIndex: '1',
    },
    '& > button': {
      width: '222px',
      height: '48px',
      backgroundColor: '#D7DEE7',
      textTransform: 'none',
      fontSize: '16px',
      fontWeight: 'bold',
      color: 'black',
      '&:hover': {
        backgroundColor: '#D7DEE7',
        opacity: '0.8',
      },
      '& > span': {
        fontFamily: 'Montserrat',
      },
    },
    '& > img': {
      position: 'absolute',
      right: '115px',
      top: '113px',
    },
    '& > div:last-child': {
      position: 'absolute',
      width: '100%',
      left: '0',
      top: '450px',
      display: 'flex',
      justifyContent: 'space-between',
      padding: '0 67px',
      '& > img': {
        cursor: 'pointer',
      },
    },
  },
  tabs: {
    position: 'relative',
    backgroundColor: 'white',
    padding: '180px 135px 168px',
    '& > div:first-child': {
      position: 'absolute',
      width: 'calc(100% - 100px)',
      height: '78px',
      top: '-39px',
      left: '50px',
      display: 'flex',
      boxShadow: '0px 5px 25px rgba(0, 0, 0, 0.2)',
      borderRadius: '3px',
      '& > button': {
        width: '20%',
        fontSize: '19px',
        fontWeight: 'bold',
        lineHeight: '25px',
        color: '#CBCBCB',
        backgroundColor: 'white',
        borderRadius: '0',
        textTransform: 'none',
      },
    },
    '& > div:last-child': {
      display: 'flex',
      boxShadow: '0px 5px 25px rgba(0, 0, 0, 0.2)',
      borderRadius: '3px',
      backgroundColor: '#D7DEE7',
      '& > div:first-child': {
        width: '40%',
        paddingBottom: '13%',
        '& > img': {
          width: '100%',
        },
      },
      '& > div:last-child': {
        width: '60%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        '& > span': {
          backgroundColor: 'white',
          fontFamily: 'HelveticaNeue',
          fontSize: '18px',
          lineHeight: '28px',
          padding: '15% 8%',
          marginLeft: '15%',
        },
        '& > p': {
          flexGrow: '1',
          display: 'flex',
          alignItems: 'center',
          margin: '10px 10px 10px 0',
          padding: '0 10% 0 23%',
          backgroundColor: 'white',
          fontFamily: 'Montserrat',
          fontSize: '35px',
          fontWeight: 'bold',
          lineHeight: '40px',
        },
      },
    },
  },
  black: {
    backgroundColor: 'black !important',
    color: 'white !important',
  },
  customer_stories: {
    backgroundImage: 'url("images/back2.png")',
    backgroundSize: 'cover',
    textAlign: 'center',
    '& > div:first-child': {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '90px 134px 67px',
      '& > p': {
        margin: '0',
        fontSize: '55px',
        fontWeight: 'bold',
        lineHeight: '75px',
        color: 'white',
      },
      '& > div': {
        display: 'flex',
        alignItems: 'center',
        color: 'white',
        '& > p': {
          margin: '0',
          fontSize: '17px',
          fontWeight: 'bold',
          lineHeight: '25px',
        },
        '& > div': {
          width: '125px',
          border: '1.5px solid white',
          backgroundColor: 'white',
          margin: '0 30px',
        },
        '& > img': {
          marginLeft: '50px',
          cursor: 'pointer',
        },
      },
    },
    '& > div:nth-child(2)': {
      display: 'flex',
      overflow: 'hidden',
      scrollBehavior: 'smooth',
      padding: '0 30%',
    },
    '& > button': {
      width: '307px',
      height: '48px',
      margin: '65px 0',
      fontSize: '16px',
      fontWeight: 'bold',
      lineHeight: '24px',
      backgroundColor: '#D7DEE7',
      borderRadius: '3px',
      textTransform: 'capitalize',
      '& > span': {
        fontFamily: 'Montserrat',
      },
      '&:hover': {
        backgroundColor: '#D7DEE7',
        opacity: '0.8',
      },
    },
  },
  card: {
    position: 'relative',
    minWidth: '100%',
    padding: '42px 48px',
    margin: '5px 20px',
    textAlign: 'left',
    backgroundSize: '100% 100%',
    '& > p': {
      margin: '0',
      padding: '35px 0 25px',
      fontFamily: 'Montserrat',
      fontSize: '45px',
      fontWeight: 'bold',
      lineHeight: '50px',
    },
    '& > span': {
      fontFamily: 'HelveticaNeue',
      fontSize: '17px',
      lineHeight: '25px',
    },
  },
  method: {
    position: 'relative',
    backgroundColor: 'white',
    padding: '0 138px',
    zIndex: '2',
    '& > div': {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
      alignItems: 'center',
      textAlign: 'center',
      height: '490px',
      transform: 'translateY(165px)',
      color: 'white',
      background: 'linear-gradient(0deg, rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.1)), linear-gradient(0deg, rgba(188, 195, 204, 0.1), rgba(188, 195, 204, 0.1)), url("images/motor.png")',
      '& > p': {
        margin: '0',
        paddingTop: '160px',
        fontSize: '55px',
        fontWeight: 'bold',
        lineHeight: '75px',
      },
      '& > span': {
        width: '60%',
        fontFamily: 'HelveticaNeue',
        fontSize: '17px',
        lineHeight: '25px',
      },
      '& > div': {
        width: '100%',
        height: '97px',
        display: 'flex',
        boxShadow: '0px 5px 25px rgba(0, 0, 0, 0.2)',
        '& > button': {
          width: '20%',
          fontSize: '19px',
          fontWeight: 'bold',
          lineHeight: '25px',
          color: '#CBCBCB',
          backgroundColor: 'white',
          borderRadius: '0',
          textTransform: 'none',
          '&:hover': {
            backgroundColor: '#eee',
          },
        },
      },
    },
  },
  flow: {
    position: 'relative',
    backgroundColor: theme.palette.background.default,
    color: 'white',
    padding: '215px 0 60px 0',
    textAlign: 'center',
    '& > div': {
      padding: '50px 160px 150px',
      display: 'flex',
      justifyContent: 'space-between',
      '& > p': {
        margin: '0',
        fontFamily: 'HelveticaNeue',
        fontSize: '24px',
        lineHeight: '54px',
        textDecorationLine: 'underline',
      },
    },
    '& > p': {
      margin: '0 140px',
      padding: '50px 60px',
      border: '6px solid #D7DEE7',
      fontSize: '27px',
      fontWeight: '600',
      lineHeight: '36px',
    },
    '& > img:last-child': {
      width: '100%',
      position: 'absolute',
      bottom: '0',
      left: '0',
    },
  },
  hello: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    backgroundColor: 'white',
    padding: '143px 0 111px',
    '& > p': {
      width: '45%',
      margin: '0',
      fontFamily: 'Montserrat',
      fontSize: '50px',
      fontWeight: '600',
      lineHeight: '50px',
      paddingBottom: '32px',
    },
    '& > button': {
      width: '190px',
      height: '48px',
      backgroundColor: '#D7DEE7',
      textTransform: 'none',
      fontSize: '16px',
      fontWeight: 'bold',
      color: 'black',
      '&:hover': {
        backgroundColor: '#D7DEE7',
        opacity: '0.8',
      },
      '& > span': {
        fontFamily: 'Montserrat',
      },
    },
  },
  bottom: {
    [theme.breakpoints.down(991)]: {
      padding: '100px 16px',
    },
  },
});

export default styles;