import { createStyles } from '@material-ui/styles';
import theme from '../../theme';

const styles = createStyles({
  voice: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    padding: '205px 135px 125px',
    color: 'white',
    '& > h1': {
      width: '100%',
      margin: '0',
      paddingBottom: '68px',
      fontSize: '70px',
      fontWeight: '600',
      lineHeight: '75px',
    },
    '& > div:not(div:last-child)': {
      width: '50%',
      display: 'flex',
      flexDirection: 'column',
      '& > img': {
        width: '100%',
        height: '400px',
        backgroundColor: '#ddd',
      },
      '& > h3': {
        margin: '0',
        paddingTop: '56px',
        fontSize: '40px',
        fontWeight: '600',
        lineHeight: '48px',
      },
      '& > p': {
        margin: '0',
        paddingTop: '32px',
        fontSize: '18px',
        lineHeight: '28px',
      },
      '& > span': {
        opacity: '0.5',
        paddingTop: '12px',
        fontSize: '18px',
        lineHeight: '28px',
      },
    },
    '& > div:last-child': {
      width: '45%',
    },
  },
  card: {
    display: 'flex',
    paddingBottom: '24px',
    '& > img': {
      width: '100%',
      height: '200px',
      marginRight: '18px',
    },
    '& > div': {
      display: 'flex',
      flexDirection: 'column',
      '& > p': {
        margin: '0',
        paddingBottom: '12px',
        fontSize: '24px',
        fontWeight: '600',
        lineHeight: '30px',
      },
      '& > span': {
        paddingBottom: '30px',
        fontFamily: 'HelveticaNeue',
        fontSize: '18px',
        lineHeight: '28px',
        opacity: '0.5',
      },
    },
  },
  video: {
    padding: '62px 128px 82px',
    backgroundColor: '#F2F8FF',
    display: 'flex',
    justifyContent: 'space-between',
    '& > div': {
      width: '48%',
      '& > iframe': {
        width: '100%',
        height: '450px',
      },
      '&:last-child': {
        paddingRight: '46px',
      },
      '& > span': {
        display: 'block',
        fontSize: '13px',
        lineHeight: '20px',
        paddingTop: '40px',
        fontWeight: '800',
      },
      '& > h3': {
        margin: '0',
        fontSize: '40px',
        lineHeight: '45px',
        paddingTop: '24px',
        fontWeight: '800',
      },
      '& > p': {
        margin: '0',
        fontSize: '20px',
        lineHeight: '30px',
        paddingTop: '24px',
      },
      '& > span:last-child': {
        fontSize: '18px',
        lineHeight: '28px',
        paddingTop: '24px',
        opacity: '0.5',
      },
    },
  },
  related: {
    padding: '135px 135px 175px',
    display: 'flex',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    color: 'white',
    '& > div': {
      width: '45%',
    },
  },
  news_hero: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    padding: '270px 135px 135px',
    color: 'white',
    '& > h3': {
      width: '50%',
      fontSize: '70px',
      lineHeight: '75px',
      fontWeight: '700',
      margin: '0',
      paddingBottom: '50px',
    },
    '& > button': {
      width: '190px',
      height: '48px',
      borderRadius: '0',
      marginBottom: '24px',
      backgroundColor: '#D7DEE7',
      textTransform: 'none',
      fontSize: '16px',
      fontWeight: 'bold',
      color: 'black',
      '&:hover': {
        backgroundColor: '#D7DEE7',
        opacity: '0.8',
      },
      '& > span': {
        fontFamily: 'Montserrat',
      },
    },
    '& > span': {
      fontSize: '18px',
      lineHeight: '28px',
      opacity: '0.5',
    },
  },
  news_view: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '90px 135px',
    color: 'white',
    '& > div:first-child': {
      width: '60%',
    },
    '& > div:last-child': {
      width: '32%',
    },
  },
  news: {
    display: 'flex',
    flexDirection: 'column',
    '& > img': {
      width: '100%',
      height: '200px',
    },
    '& > p': {
      margin: '0',
      padding: '32px 0 16px',
      fontSize: '10px',
      lineHeight: '12px',
      textTransform: 'uppercase',
    },
    '& > h3': {
      margin: '0',
      paddingBottom: '12px',
      fontSize: '25px',
      lineHeight: '112.3%',
    },
    '& > span': {
      fontFamily: 'HelveticaNeue',
      fontSize: '18px',
      lineHeight: '28px',
      opacity: '0.5',
    },
  },
  news_related: {
    display: 'flex',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    padding: '0 135px',
    color: 'white',
    '& > div': {
      width: '32%',
    },
    '& > button': {
      width: '190px',
      height: '48px',
      borderRadius: '0',
      margin: '100px auto',
      backgroundColor: '#D7DEE7',
      textTransform: 'none',
      fontSize: '16px',
      fontWeight: 'bold',
      color: 'black',
      '&:hover': {
        backgroundColor: '#D7DEE7',
        opacity: '0.8',
      },
      '& > span': {
        fontFamily: 'Montserrat',
      },
    },
  },
  news_featured: {
    display: 'flex',
    alignItems: 'center',
    padding: '170px 135px',
    color: 'white',
    '& > *': {
      width: '50%',
    },
    '& > div': {
      display: 'flex',
      flexDirection: 'column',
      padding: '100px 64px',
      '& > p': {
        margin: '0',
        fontSize: '13px',
        lineHeight: '20px',
        textTransform: 'uppercase',
      },
      '& > h3': {
        margin: '0',
        padding: '25px 0 12px',
        fontSize: '45px',
        lineHeight: '112.3%',
      },
      '& > span': {
        fontFamily: 'HelveticaNeue',
        fontSize: '18px',
        lineHeight: '28px',
        opacity: '0.5',
      },
    },
  },
  detail: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '200px 80px 100px',
    color: 'white',
    '& > h4': {
      margin: '0',
      fontSize: '18px',
      lineHeight: '28px',
    },
    '& > h3': {
      width: '50%',
      margin: '0',
      padding: '16px 0',
      fontSize: '40px',
      lineHeight: '48px',
      fontWeight: '700',
      textAlign: 'center',
    },
    '& > p': {
      width: '45%',
      margin: '0',
      paddingBottom: '28px',
      fontSize: '18px',
      lineHeight: '28px',
    },
    '& > span': {
      fontSize: '14px',
      lineHeight: '28px',
      opacity: '0.5',
    },
    '& > p#center': {
      textAlign: 'center',
    },
    '& > img#top': {
      width: '100%',
      height: '768px',
      margin: '42px 0 88px',
    },
    '& > img': {
      backgroundColor: '#ddd',
      width: '65%',
      height: '400px',
      marginTop: '60px',
    },
    '& > div': {
      width: '65%',
      display: 'flex',
      justifyContent: 'space-between',
      padding: '16px 0 88px',
      '& > img': {
        width: '49%',
        height: '500px',
        backgroundColor: '#ddd',
      },
    },
  },
  detail_related: {
    backgroundColor: '#F2F8FF',
    padding: '120px 135px 90px',
    '& > h3': {
      margin: '0',
      paddingBottom: '80px',
      fontFamily: 'HelveticaNeue',
      fontSize: '40px',
      lineHeight: '48px',
      fontWeight: '700',
    },
    '& > div': {
      width: '100%',
      display: 'flex',
      justifyContent: 'space-between',
      '& > div': {
        width: '32%',
      },
    },
  },
  detail_card: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
    paddingBottom: '24px',
    '& > img': {
      width: '100%',
      height: '250px',
      marginBottom: '24px',
      backgroundColor: '#ddd',
    },
    '& > p': {
      margin: '0',
      padding: '0 16px 16px',
      fontSize: '24px',
      fontWeight: '600',
      lineHeight: '30px',
    },
    '& > span': {
      padding: '0 16px 85px',
      fontFamily: 'HelveticaNeue',
      fontSize: '16px',
      lineHeight: '28px',
    },
  },
});

export default styles;