import { createStyles } from '@material-ui/styles';
import theme from '../../theme';

const styles = createStyles({
  hero: {
    position: 'relative',
    height: '900px',
    padding: '215px 135px',
    display: 'flex',
    flexDirection: 'column',
    color: 'white',
    '& > div:first-child': {
      display: 'flex',
      alignItems: 'center',
      paddingBottom: '16px',
      '& > span': {
        fontSize: '17px',
        lineHeight: '25px',
        paddingLeft: '15px',
      }
    },
    '& > span': {
      maxWidth: '750px',
      fontSize: '70px',
      fontWeight: 'bold',
      lineHeight: '75px',
      letterSpacing: '-1px',
      zIndex: '1',
      paddingBottom: '48px',
    },
    '& > p': {
      maxWidth: '550px',
      margin: '0',
      fontSize: '30px',
      lineHeight: '40px',
      zIndex: '1',
    },
  },
  business_overview: {
    display: 'flex',
    padding: '110px 150px 150px',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
    '& > p': {
      margin: '0',
      fontSize: '45px',
      fontWeight: 'bold',
      lineHeight: '50px',
      paddingBottom: '20px',
    },
    '& > span': {
      maxWidth: '555px',
      fontSize: '18px',
      lineHeight: '28px',
      paddingBottom: '48px',
    },
    '& > img': {
      width: '100%',
      height: '350px',
      backgroundColor: 'lightblue',
    },
  },
  method: {
    display: 'flex',
    padding: '113px 135px',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
    '& > p': {
      margin: '0',
      fontSize: '45px',
      fontWeight: 'bold',
      lineHeight: '50px',
      paddingBottom: '16px',
    },
    '& > span': {
      maxWidth: '555px',
      fontSize: '18px',
      lineHeight: '28px',
      paddingBottom: '80px',
    },
    '& > div': {
      padding: '36px 0',
      width: '100%',
      display: 'flex',
      justifyContent: 'space-between',
      '& > p': {
        width: '33.33%',
        margin: '0',
        fontFamily: 'HelveticaNeue',
        fontSize: '24px',
        lineHeight: '54px',
      },
    },
    '& > p:last-child': {
      margin: '166px 0 0',
      padding: '50px 60px',
      border: '6px solid #D7DEE7',
      fontSize: '27px',
      fontWeight: '600',
      lineHeight: '36px',
    }
  },
  story: {
    padding: '120px 135px 160px',
    color: 'white',
    '& > div': {
      position: 'relative',
      backgroundColor: 'lightblue',
      display: 'flex',
      flexDirection: 'column',
      marginLeft: '10%',
      padding: '48px 10px 24px 20%',
      '& > p': {
        width: '60%',
        margin: '0',
        fontSize: '35px',
        lineHeight: '40px',
        fontWeight: 'bold',
      },
      '& > div': {
        display: 'flex',
        padding: '32px 0 24px',
        '& > span': {
          padding: '32px 0',
          fontSize: '18px',
          lineHeight: '28px',
        },
        '& > div': {
          marginLeft: '45px',
          borderLeft: '1px solid blue',
          paddingLeft: '36px',
          '& > p': {
            margin: '0',
            fontSize: '67px',
            lineHeight: '60px',
            fontWeight: 'bold',
          },
          '& > span': {
            display: 'block',
            padding: '16px 0 46px',
            fontSize: '17px',
            lineHeight: '25px',
          },
        },
      },
      '& > button': {
        width: '190px',
        height: '48px',
        textTransform: 'none',
      },
      '& > img': {
        width: '25%',
        height: '350px',
        backgroundColor: 'blue',
        position: 'absolute',
        left: '-10%',
        bottom: '0',
      },
    },
  },
  government_overview: {
    display: 'flex',
    padding: '85px 150px 0',
    justifyContent: 'space-between',
    color: 'white',
    '& > div': {
      width: '33%',
      display: 'flex',
      flexDirection: 'column',
      '& > p': {
        margin: '0',
        fontSize: '45px',
        fontWeight: 'bold',
        lineHeight: '50px',
        paddingBottom: '48px',
      },
      '& > span': {
        maxWidth: '555px',
        fontSize: '18px',
        lineHeight: '28px',
      },
    },
  },
  investments_overview: {
    display: 'flex',
    padding: '85px 150px',
    justifyContent: 'space-between',
    color: 'white',
    '& > img': {
      width: '60%',
    },
    '& > div': {
      width: '40%',
      display: 'flex',
      flexDirection: 'column',
      paddingRight: '10%',
      '& > p': {
        margin: '0',
        fontSize: '45px',
        fontWeight: 'bold',
        lineHeight: '50px',
        paddingBottom: '48px',
      },
      '& > span': {
        maxWidth: '555px',
        fontSize: '18px',
        lineHeight: '28px',
      },
    },
  },
  philanthropy_overview: {
    backgroundColor: '#F2F8FF',
    padding: '120px 150px',
    '& > div:first-child': {
      padding: '0 35px 0 100px',
      '& > p': {
        margin: '0',
        fontSize: '45px',
        fontWeight: 'bold',
        lineHeight: '50px',
      },
      '& > div': {
        width: '100%',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        '& > span': {
          width: '60%',
          fontSize: '18px',
          lineHeight: '28px',
        },
        '& > p': {
          width: '35%',
          margin: '0',
          padding: '40px',
          fontSize: '24px',
          lineHeight: '32px',
          border: '6px solid #E1EEFF',
        },
      },
    },
    '& > div:last-child': {
      paddingTop: '110px',
      display: 'flex',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      '& > *': {
        width: '48%',
      },
      '& > img': {
        height: '500px',
      },
      '& > span': {
        paddingTop: '24px',
        fontSize: '18px',
        lineHeight: '28px',
      },
    },
  },
  motorsports_overview: {
    padding: '110px 150px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
    '& > p': {
      width: '50%',
      margin: '0',
      paddingBottom: '20px',
      fontSize: '45px',
      lineHeight: '50px',
      fontWeight: 'bold',
    },
    '& > span': {
      width: '50%',
      paddingBottom: '48px',
      fontSize: '18px',
      lineHeight: '28px',
    },
    '& > img': {
      width: '100%',
      height: '300px',
      backgroundColor: '#EEE',
    },
  },
  gallery: {
    padding: '300px 0 150px',
  },
  hello: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    padding: '121px 0 127px',
    '& > p': {
      width: '45%',
      textAlign: 'center',
      margin: '0',
      fontFamily: 'Montserrat',
      fontSize: '50px',
      fontWeight: '600',
      lineHeight: '50px',
      paddingBottom: '32px',
    },
    '& .MuiOutlinedInput-root': {
      width: '380px',
      borderRadius: '0',
      marginBottom: '24px',
      backgroundColor: 'white',
      fontFamily: 'HelveticaNeue',
      fontSize: '14px',
      lineHeight: '28px',
      '& > input': {
        paddingLeft: '24px',
      },
    },
    '& .MuiOutlinedInput-multiline': {
      paddingLeft: '24px',
    },
    '& > button': {
      width: '190px',
      height: '48px',
      borderRadius: '0',
      marginTop: '16px',
      backgroundColor: '#D7DEE7',
      textTransform: 'none',
      fontSize: '16px',
      fontWeight: 'bold',
      color: 'black',
      '&:hover': {
        backgroundColor: '#D7DEE7',
        opacity: '0.8',
      },
      '& > span': {
        fontFamily: 'Montserrat',
      },
    },
  },
});

export default styles;